<a href="https://colab.research.google.com/github/24f1000525/BI-Agent/blob/main/Dataset_Api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Loader

In [23]:
from sklearn.datasets import load_diabetes

In [24]:
data=load_diabetes()

In [25]:
type(data)

sklearn.utils._bunch.Bunch

In [26]:
data.data[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087]])

In [27]:
data.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [28]:
data.data.shape

(442, 10)

In [29]:
data.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [30]:
?load_diabetes

In [31]:
data.target.shape

(442,)

In [32]:
feature_matrix,label_vector=load_diabetes(return_X_y=True)


In [33]:
type(feature_matrix)

numpy.ndarray

In [34]:
feature_matrix.shape

(442, 10)

In [35]:
feature_matrix[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087]])

In [36]:
label_vector[:5]

array([151.,  75., 141., 206., 135.])

In [37]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee

## Fetcher

In [38]:
from sklearn.datasets import fetch_california_housing
?fetch_california_housing

In [39]:
housing_data=fetch_california_housing()

In [40]:
print(housing_data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per ce

In [41]:
housing_data.data.shape

(20640, 8)

In [42]:
housing_data.data[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

In [43]:
housing_data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [44]:
housing_data.target_names

['MedHouseVal']

### fetch_openml

In [46]:
from sklearn.datasets import fetch_openml

In [48]:
x,y=fetch_openml('mnist_784',return_X_y=True)
print(x.shape,y.shape)

/usr/local/lib/python3.12/dist-packages/sklearn/datasets/_openml.py:110: UserWarning: A network error occurred while downloading https://api.openml.org/api/v1/json/data/list/data_name/mnist_784/limit/2/status/active/. Retrying...
  warn(


KeyboardInterrupt: 

## Generators

#### make_regression

In [49]:
from sklearn.datasets import make_regression
?make_regression

Lets generate 100 samples with 5 features for a single label regression problem.

In [50]:
x,y=make_regression(n_samples=100,n_features=5,n_targets=1,shuffle=True,random_state=42)

In [51]:
x.shape

(100, 5)

In [52]:
y.shape

(100,)

make_classification

In [54]:
from sklearn.datasets import make_classification
?make_classification

In [55]:
x,y=make_classification(n_samples=100,n_features=10,n_classes=2,n_clusters_per_class=1,shuffle=True,random_state=42)

In [56]:
x.shape

(100, 10)

In [58]:
y[:5]

array([1, 1, 1, 1, 0])

make_multilabel_classification

In [59]:
from sklearn.datasets import make_multilabel_classification
?make_multilabel_classification

In [61]:
x,y=make_multilabel_classification(n_samples=100,n_features=10,n_classes=2,n_labels=2,random_state=42)

In [62]:
x.shape


(100, 10)

In [63]:
y[:5]

array([[0, 1],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1]])

In [64]:
y.shape

(100, 2)

make_blobs enables us to generate random data for cluster

In [67]:
from sklearn.datasets import make_blobs
?make_blobs

In [70]:
x,y=make_blobs(n_samples=10,n_features=2,centers=2,cluster_std=1,shuffle=True,random_state=42)

In [71]:
y

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 1])

In [72]:
x

array([[ 2.914961  ,  1.41088215],
       [-2.97261532,  8.54855637],
       [-0.92998481,  9.78172086],
       [ 3.62704772,  2.28741702],
       [-2.743351  ,  8.78014917],
       [ 3.73185476,  0.56086598],
       [ 4.70740704,  0.5484215 ],
       [-2.26723535,  7.10100588],
       [-2.97867201,  9.55684617],
       [ 6.10552761,  1.74739338]])